version: "3.8"

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile을 참조하여 이미지 빌드
    working_dir: /app
    command: ["python3", "main.py"]
    volumes:
      - .:/app  # 호스트 디렉토리를 컨테이너의 /app에 마운트
